@base_address = http://localhost:8000/api
@TOKEN =
@ID =

############################################################AUTH
### Register
POST {{base_address}}/register
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "testpassword",
  "firstname": "test",
  "lastname": "test",
  "address": "123 Main Street",
  "city": "Paris",
  "postal_code": "75001",
  "phone": "0612345678",
  "is_pro": false
}

> {%
    // parse the JSON response
    const data = JSON.parse(response.body);
    // store token in a global variable
    client.global.set("ID", data.user.id);
%}

###  Login after register
POST {{base_address}}/login
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "testpassword"
}

> {%
    // parse the JSON response
    const data = JSON.parse(response.body);
    // store token in a global variable
    client.global.set("TOKEN", data.authorisation.token);
%}

### Refresh
GET {{base_address}}/refresh
Authorization: Bearer {{TOKEN}}

### Logout
POST {{base_address}}/logout
Authorization: Bearer {{TOKEN}}

############################################################ USER
### GET USER INFOS
GET {{base_address}}/user
Authorization: Bearer {{TOKEN}}

### Update user infos
POST


############################################################ ADMIN USER
### Login token
POST {{base_address}}/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "adminadmin"
}

> {%
    // parse the JSON response
    const data = JSON.parse(response.body);
    // store token in a global variable
    client.global.set("TOKEN", data.authorisation.token);
%}

############################################################SERVICES
### GET all services by language:  1 = fr, 2 = en
GET {{base_address}}/service/lang-1

### GET one service
GET {{base_address}}/service/1

### POST one service
POST {{base_address}}/service
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "title": "Hello lucas ",
    "price_in_cent": 1000,
    "duration_in_day": 2,
    "is_per_person": "true",
    "language_id": 1
}

### PUT one service
POST {{base_address}}/service/2
Content-Type: application/json

{
    "title": "Hello et pas qu'un peu",
    "price_in_cent": 1000,
    "duration_in_day": 2,
    "is_per_person": "true",
    "language_id": 2
}

### DELETE one service
DELETE {{base_address}}/service/3



############################################################CONTENTS
### GET all contents by language:  1 = fr, 2 = en
GET {{base_address}}/content/lang-2

### GET one content
GET {{base_address}}/content/1

### POST one content
POST {{base_address}}/content
Content-Type: application/json

{
    "name": "luuuuuuucas",
    "title": "lucas est pd",
    "short_description": "Petite description comme ça à la cool",
    "description": "Grande description comme ça aussi à la cool",
    "landing_page_display": "true",
    "navbar_display": "false",
    "language_id": 1

}

### PUT one content
POST {{base_address}}/content/2
Content-Type: application/json

{
    "name": "luuuuuuucas",
    "title": "lucas est pd",
    "short_description": "Petite description comme ça à la cool",
    "description": "Grande description comme ça aussi à la cool",
    "landing_page_display": "true",
    "navbar_display": "false",
    "language_id": 2
}

### DELETE one content
DELETE {{base_address}}/content/3



############################################################NEWS
### GET all news by language:  1 = fr, 2 = en
GET {{base_address}}/news/lang-1

### GET one news
GET {{base_address}}/news/1

### POST one news
POST {{base_address}}/news
Content-Type: application/json

{
    "title": "lucas est pd",
    "short_description": "Petite description comme ça à la cool",
    "description": "Grande description comme ça aussi à la cool",
    "language_id": 2
}

### PUT one news
POST {{base_address}}/news/2
Content-Type: application/json

{
    "title": "lucas est pd",
    "short_description": "Petite description comme ça à la cool",
    "description": "Grande description comme ça aussi à la cool",
    "language_id": 1
}

### DELETE one news
DELETE {{base_address}}/news/3



############################################################ROOMS
### GET all room by language:  1 = fr, 2 = en
GET {{base_address}}/room/lang-2

### GET one room
GET {{base_address}}/room/1

### POST one room
POST {{base_address}}/room
Content-Type: application/json

{
    "number": 244,
    "name": "Kling",
    "description": "Nesciunt nostrum autem amet quia consequatur odio.",
    "rooms_category_id": 2,
    "language_id": 1
}

### PUT one room
POST {{base_address}}/room/2
Content-Type: application/json

{
    "number": 244,
    "name": "Kling",
    "description": "Nesciunt nostrum autem amet quia consequatur odio.",
    "rooms_category_id": 2,
    "language_id": 2
}

### DELETE one room
DELETE {{base_address}}/room/5




############################################################REVIEWS
### GET all reviews
GET {{base_address}}/review

### GET one review
GET {{base_address}}/review/1

### POST one review
POST {{base_address}}/review
Content-Type: application/json

{
    "rate": 5,
    "review_content": "not bad at all",
    "user_id": 546
}

### PUT one review
POST {{base_address}}/review/2
Content-Type: application/json

{
    "rate": 2,
    "review_content": "suck my dick",
    "user_id": 69
}

### DELETE one review
DELETE {{base_address}}/review/5


############################################################FEATURES
### GET all room-features by language:  1 = fr, 2 = en
GET {{base_address}}/rooms-feature/lang-1

### GET one rooms-feature
GET {{base_address}}/rooms-feature/1

### POST one rooms-feature
POST {{base_address}}/rooms-feature
Content-Type: application/json

{
    "name": "Tv",
    "description": "Une télévision à écran plat avec une large sélection de chaînes locales et internationales, permettant aux clients de se détendre et de profiter de divertissements dans leur chambre.",
    "rooms_categories": [1, 2],
    "language_id": 2
}

### PUT one rooms-feature
POST {{base_address}}/rooms-feature/2
Content-Type: application/json

{
    "name": "Tv",
    "description": "Une télévision à écran plat avec une large sélection de chaînes locales et internationales, permettant aux clients de se détendre et de profiter de divertissements dans leur chambre.",
    "rooms_categories": [1, 2],
    "language_id": 1
}

### DELETE one rooms-category
DELETE {{base_address}}/rooms-category/5


############################################################CATEGORIES
### GET all rooms-categories  by language:  1 = fr, 2 = en
GET {{base_address}}/rooms-category/lang-2

### GET one rooms-category
GET {{base_address}}/rooms-category/1

### POST one rooms-category
POST {{base_address}}/rooms-category
Content-Type: application/json

{
    "name": "StandardRooms2",
    "description": "Spacious room with a great vi,nhg,g,,hg,ew.",
    "price_in_cent": 1000000,
    "bed_size": 701,
    "rooms_features": [1,2],
    "language_id": 1,
    "images": []
}

### PUT one rooms-category
POST {{base_address}}/rooms-category/2
Content-Type: application/json

{
    "name": "StandardRooms2",
    "description": "Spacious room with a great vi,nhg,g,,hg,ew.",
    "price_in_cent": 1000000,
    "bed_size": 701,
    "rooms_features": [1,2],
    "language_id": 2,
    "images": []
}

### DELETE one rooms-category
DELETE {{base_address}}/rooms-category/5


############################################################LANGUAGE
### GET all language
GET {{base_address}}/language

### GET one language
GET {{base_address}}/language/1

### POST one language
POST {{base_address}}/language
Content-Type: application/json

{
    "lang": "sp"
}

### PUT one language
POST {{base_address}}/language/2
Content-Type: application/json

{
    "lang": "it"
}

### DELETE one language
DELETE {{base_address}}/language/3
